---
- hosts: all
  become: true
  vars:
    app_name: "myapp"
    app_path: "/opt/{{ app_name }}"
    node_version: "14.x"
    npm_packages:
      - express
      - socket.io  
  tasks:
    - name: Update Node.js and npm
      apt:
        update_cache: yes

    # Install Node.js and NPM
    - name: Install curl
      apt:
        name: curl
        state: present
        update_cache: yes
      become: yes

    - name: Install dirmngr, apt-transport-https, lsb-release, and ca-certificates
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - dirmngr
        - apt-transport-https
        - lsb-release
        - ca-certificates
      become: yes

    - name: Add Node.js repository
      shell: curl -sL https://deb.nodesource.com/setup_{{ node_version }} | bash -
      become: yes
      ignore_errors: yes

    - name: Install Node.js
      apt:
        name: nodejs
        state: present
        update_cache: yes
      become: yes
      ignore_errors: yes

    - name: Install npm
      apt:
        name: npm
        state: present
        update_cache: yes
      become: yes

    # Clone the Git repository
    - name: Clone the Git repository
      git:
        repo: "https://github.com/myitserver/myapp.git"
        dest: "{{ app_path }}"
        clone: yes

    # Install application dependencies
    #    - name: Install application dependencies
    #  npm:
    #    name: "{{ ['express', 'socket'] }}"
    #    path: /opt/myapp  
    #    state: present  


    - name: Install PM2
      npm:
        name: pm2
        global: yes

    # Set up the application environment
    - name: Set up the application environment
      copy:
        dest: "{{ app_path }}/.env"
        content: |
          NODE_ENV=production
          PORT=3000

    # Start the application using PM2
    - name: Start the application using PM2
      become: yes
      command: pm2 start server.js --name myapp --ignore-watch "node_modules"
      args:
        chdir: /opt/myapp
          # npm:
          # path: "{{ app_path }}"
          # args: "start server.js --name={{ app_name }} --watch"
