---
- name: Create directory and install npm package
  hosts: all
  become: yes

  tasks:
    - name: Install Node.js 12 and NPM
  become: yes
  apt:
    name:
      - curl
      - gnupg
  environment:
    DEBIAN_FRONTEND: noninteractive

- name: Add Node.js 12.x repository
  become: yes
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present
  apt_repository:
    repo: deb https://deb.nodesource.com/node_12.x {{ ansible_distribution_release }} main
    state: present
    filename: nodesource.list

- name: Install Node.js and NPM
  become: yes
  apt:
    name:
      - nodejs

  - name: Create directory
    file:
      path: /home/ubuntu/myapp
      state: directory

  - name: Create package.json file
    command: npm init -y
    args:
      chdir: /home/ubuntu/myapp

  - name: Install socket.io
    npm:
      name: socket.io
      path: /home/ubuntu/myapp
